version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    container_name: 'backend'
    ports:
      - '$APP_PORT:$APP_PORT'
    env_file:
      - .env
    tty: true
